const filmsArray = [
  {
    _id: 1,
    title: "33 слова о дизайне",
    link: "https://wallpapersprinted.com/download/2/view_of_manarola_cinque_terre_italy-wallpaper-5120x3200.jpg",
    save: true,
    duration: "1ч 30м",
  },
  {
    _id: 2,
    title: "Киноальманах «100 лет дизайна»",
    link: "https://get.wallhere.com/photo/1920x1200-px-bridge-bridges-gate-golden-1783391.jpg",
    save: true,
    duration: "1ч 30м",
  },
  {
    _id: 3,
    title: "В погоне за Бенкси",
    link: "https://www.sunhome.ru/i/wallpapers/138/belii-zamok.orig.jpg",
    save: false,
    duration: "1ч 30м",
  },
  {
    _id: 4,
    title: "Баския: Взрыв реальности",
    link: "https://s1.1zoom.ru/big3/984/Canada_Parks_Lake_Mountains_Forests_Scenery_Rocky_567540_3840x2400.jpg",
    save: false,
    duration: "1ч 30м",
  },
  {
    _id: 5,
    title: "Бег это свобода",
    link: "https://mobimg.b-cdn.net/v3/fetch/fb/fbb6ca823f2f99c48dd083b55bfc0b35.jpeg",
    save: false,
    duration: "1ч 30м",
  },
  {
    _id: 6,
    title: "Книготорговцы ",
    link: "https://get.wallhere.com/photo/coniferous-forest-mountains-height-greatness-green-landscape-1070576.jpg",
    save: true,
    duration: "1ч 30м",
  },
  {
    _id: 7,
    title: "Когда я думаю о Германии ночью",
    link: "https://www.sunhome.ru/i/wallpapers/144/kamni-v-reke.orig.jpg",
    save: true,
    duration: "1ч 30м",
  },
  {
    _id: 8,
    title: "Gimme Danger: История Игги и The Stooge...",
    link: "https://s1.1zoom.ru/big7/567/Grasslands_Scenery_Trail_480883.jpg",
    save: true,
    duration: "1ч 30м",
  },
  {
    _id: 9,
    title: "Дженис: Маленькая девочка грустит",
    link: "https://get.wallhere.com/photo/1920x1200-px-forest-lake-landscape-Moraine-Lake-mountain-nature-1078901.jpg",
    save: false,
    duration: "1ч 30м",
  },
  {
    _id: 10,
    title: "Соберись перед прыжком",
    link: "https://get.wallhere.com/photo/1920x1200-px-Lamborghini-McLaren-rain-supercars-1051492.jpg",
    save: true,
    duration: "1ч 30м",
  },
  {
    _id: 11,
    title: "Пи Джей Харви: A dog called money",
    link: "https://s1.1zoom.ru/big3/43/Waves_Sea_Ocean_481822.jpg",
    save: false,
    duration: "1ч 30м",
  },
  {
    _id: 12,
    title: "По волнам: Искусство звука в кино",
    link: "https://www.sunhome.ru/i/wallpapers/109/kamni.orig.jpg ",
    save: true,
    duration: "1ч 30м",
  },
];

export default filmsArray;
